baseURL = "https://dkremez.github.io/"
languageCode = "en"
title = "Dzmitry Kremez"
theme = "devresume-theme"
googleAnalytics = "UA-153716840-1"

# Page settings
[params]
author = "Dzmitry Kremez"
description = "Senior Product Engineer - Specializing in Software Development, AI Solutions and Engineering Leadership"
primaryColor = "#665b50"
textPrimaryColor = "#292929"

[params.profile]
enable = true
name = "Dzmitry Kremez"
tagline = "Senior Product Engineer"
avatar = "avatar-latest.jpg"

[params.contact]
enable = true
location = "Dublin"
[[params.contact.list]]
icon = "fas fa-phone-square"
url = "tel:+353876870576"
text = "+353876870576"
[[params.contact.list]]
icon = "fas fa-envelope-square"
url = "mailto:mr.dkremez@gmail.com"
text = "mr.dkremez@gmail.com"
[[params.contact.list]]
icon = "fas fa-globe"
url = "https://github.com/dkremez"
text = "https://github.com/dkremez"


[params.skills]
enable = true

[[params.skills.list]]
title = "Technical Expertise"
[[params.skills.list.items]]
details = "AI Solutions Architecture"
[[params.skills.list.items]]
details = "Full-Stack Development (JavaScript/TypeScript, React, Ruby on Rails)"
[[params.skills.list.items]]
details = "Cloud Infrastructure (AWS, GCP)"
[[params.skills.list.items]]
details = "System Design & Architecture"
[[params.skills.list.items]]
details = "Security & Performance Optimization"
[[params.skills.list.items]]
details = "CI/CD & DevOps"

[[params.skills.list]]
title = "Leadership"
[[params.skills.list.items]]
details = "Engineering Team Leadership"
[[params.skills.list.items]]
details = "Technical Strategy"
[[params.skills.list.items]]
details = "Mentorship & Team Development"
[[params.skills.list.items]]
details = "Product Strategy"
[[params.skills.list.items]]
details = "Stakeholder Management"
[[params.skills.list.items]]
details = "Cross-functional Collaboration"


[params.education]
enable = true

[[params.education.list]]
degree = "MSc in Computer Science (Unfinished)"
university = "Belarusian State University of Informatics and Radioelectronics"
dates = "2014 - 2015"
[[params.education.list]]
degree = "BSc in Computer Science"
university = "Belarusian State Academy of Telecommunications"
dates = "2007 - 2014"


[params.awards]
enable = false

[[params.awards.list]]
name = "iTechArt Hackathon 1st place"
body = "iTechArt Hackathon"
date = "2015"

[params.languages]
enable = true

[[params.languages.list]]
name = "English"
level = "Professional (Upper-Intermediate)"
[[params.languages.list]]
name = "Russian"
level = "Native"


[params.interests]
enable = true

[[params.interests.list]]
name = "Traveling"
[[params.interests.list]]
name = "Driving"
[[params.interests.list]]
name = "Reading"
[[params.interests.list]]
name = "Snowboarding"
[[params.interests.list]]
name = "Exercises"

[params.summary]
enable = true
text = '''
Distinguished Senior Product Engineer with 10+ years of expertise in full-stack development, AI solutions and engineering leadership.
Recognized for combining technical excellence with product vision to deliver high-impact solutions. Successfully led the development
of AI-powered customer experience platforms and scaled engineering teams. Known for commitment to clean
architecture, mentorship, and driving technical innovation that delivers measurable business results.
'''

[params.experience]
enable = true

[[params.experience.list]]
title = "Senior Product Engineer"
dates = "2022 - Present"
company = "Intercom R&D Unlimited Company"
details = "Leading AI and product initiatives in customer messaging platform:"
[[params.experience.list.items]]
details = "Enhanced AI Agent security options through implementation of advanced verification systems (OTP, Contextual Identification, JWT)"
[[params.experience.list.items]]
details = "Architected and delivered cross-platform Tickets in Messenger feature, driving measurable improvements in support efficiency"
[[params.experience.list.items]]
details = "Implemented security enhancements resulting in 50% higher secure installation success rate"
[[params.experience.list.items]]
details = "Core contributor to Fin AI Agent launch, enabling automated assistance for 20K+ customers with 100M+ end-users"
[[params.experience.list.items]]
details = "Led architectural improvements for Messenger v5 platform upgrade"

[[params.experience.list]]
title = "Group -> Department Manager"
dates = "2018 - 2022"
company = "iTechArt Group"
details = "Scaled and led engineering organization:"
[[params.experience.list.items]]
details = "Drove 200% department and 500% group revenue growth while maintaining profit margins targets"
[[params.experience.list.items]]
details = "Maintained 95% client satisfaction through strategic account management"
[[params.experience.list.items]]
details = "Built and led high-performing management structure of 5 group managers and 10+ team leads, driving strategic alignment and operational excellence"
[[params.experience.list.items]]
details = "Scaled engineering team from 8 to 150+ professionals with 95% retention rate"
[[params.experience.list.items]]
details = "Established university education programs and engineering knowledge-sharing initiatives"

[[params.experience.list]]
title = "Software Engineer -> Lead Software Engineer"
dates = "2013 - 2018"
company = "iTechArt Group"
details = "Technical leadership and architecture:"
[[params.experience.list.items]]
details = "Delivered 3 major client projects with 100% on-time completion and exceptional customer feedback"
[[params.experience.list.items]]
details = "Implemented complex technical features including real-time analytics and distributed caching systems"
[[params.experience.list.items]]
details = "Promoted to leadership role based on consistent technical excellence and client satisfaction"
[[params.experience.list.items]]
details = "Regular speaker at company tech talks, sharing expertise in scalable architecture and best practices"
[[params.experience.list.items]]
details = "Mentored 20+ engineers to senior positions through hands-on guidance and technical leadership"
[[params.experience.list.items]]
details = "Served as go-to technical expert for resolving complex bugs and unblocking critical issues across multiple teams"

[params.projects]
enable = true

[[params.projects.list]]
title = "Intercom / Messenger Team"
meta = "Senior Product Engineer"
tagline = "Enterprise-scale business messaging platform enabling companies to communicate with customers through AI-powered solutions and real-time chat."

[[params.projects.list]]
title = "CoverWallet (AON)"
meta = "Lead Software Engineer"
tagline = "Digital insurance platform providing automated business insurance management and concierge services for enterprises."

[[params.projects.list]]
title = "Harvest"
meta = "Senior Software Engineer"
tagline = "Digital content platform for investment organizations to distribute insights and analysis to the investor community."

[[params.projects.list]]
title = "Caredox"
meta = "Software Engineer"
tagline = "CareDox is a care coordination platform for parents and schools. It automate and streamline information collection and access to improve child safety."


[[params.projects.list]]
title = "Early Career Projects"
meta = "Software Engineer"
tagline = "Led development on various SaaS platforms including healthcare coordination (CareDox), appointment booking systems, and learning management solutions. Specialized in user-centric applications with focus on data security and scalability."


[params.information]
enable = true

[[params.information.list]]
title = "Testimonials"
[[params.information.list.items]]
details = "Tomás Pérez - Software Engineering Leader (Ex Amazon, Spotify, Tuenti)"
[[params.information.list.items]]
details = '''
"One of the most skilled software engineers I've ever met. Combines amazing technical skills with great attitude,
always committed and helpful. Cares deeply about solution quality with focus on clean code and architecture.
A key player in every project, almost guaranteeing success and on-time delivery. Excellent at mentoring and
developing both technical and soft skills in team members."
'''

[[params.information.list]]
title = "Intercom R&D United Company Contacts"
[[params.information.list.items]]
details = "124 St Stephen's Green, Dublin 2, D02 C628"
[[params.information.list.items]]
details = "Engineering Manager: Dale Cantwell, <dale@intercom.io> "

[[params.information.list]]
title = "iTechArt Company Contacts"
[[params.information.list.items]]
details = "Address: Minsk, 220007, st. Tolstoy, 10, Phone: +375333876163"
[[params.information.list.items]]
details = "Unit Director: Mikhail Linnik, mikhail.linnik@itechart-group.com, +375447087579"

[[params.information.list]]
title = "Additional Education"
[[params.information.list.items]]
details = "2021 · Blockchain Development & Cryptocurrency (Solidity, Foundations, Core Concepts)"
[[params.information.list.items]]
details = "2019 · ManageIT.by - Hard Skills for IT-Managers"
[[params.information.list.items]]
details = "2018 · Machine Learning Fundamentals (Tensor.by, Belhard)"
[[params.information.list.items]]
details = "2017 · Cronis.by - Algorithms and Data Structures"
[[params.information.list.items]]
details = "2012-2013 · Enterprise Software Development (Java SE/EE, Production Systems)"

[[params.information.list]]
title = "Interests"
details = "Travelings, Driving, Reading, Snowboarding, Exercises"


[params.social]
enable = true

[[params.social.list]]
icon = "fab fa-github-square"
url = "//github.com/dkremez"
title = "dkremez"
[[params.social.list]]
icon = "fab fa-linkedin"
url = "//linkedin.com/in/dzmitry-kremez-290a8181"
title = "dzmitry-kremez"
[[params.social.list]]
icon = "fab fa-twitter-square"
url = "//twitter.com/dima_kremez"
title = "@dima_kremez"
